guest/urls.py
from django.contrib import admin
from django.urls import path
from . import views as guest_view
from django.conf.urls import include, url

app_name = 'guest'
urlpatterns = [
    path('', guest_view.start, name='start'),
    path('register/', guest_view.register, name='register'),
    path('login/', guest_view.user_login, name='login'),
    path(r'login/home/', guest_view.home, name='home'),
    path(r'login/select/<int:res_id>/', guest_view.select, name='select'),
    # url(r'profile/^$', guest_view.profile, name='profile'),
    path(r'login/edit/<int:res_id>/', guest_view.edit, name='edit'),
    path(r'login/confirm/<int:res_id>/', guest_view.confirm, name='confirm'),
    path(r'login/cancel/<int:res_id>/', guest_view.cancel, name='cancel'),
    path(r'login/pdf/<int:res_id>/', guest_view.generate_pdf, name='pdf'),
    path(r'login/bookings/', guest_view.bookings, name='bookings'),
    path('logout/', guest_view.logout_view, name='logout'),
]

hms/urls.py
from django.contrib import admin
from django.urls import path
from selection import views
from django.conf.urls import include, url
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^', include(('selection.urls', 'selection'), namespace='selection')),
    url(r'^guest/', include('guest.urls', namespace='guest')),
    path('', views.start, name='start'),
    path('hms/', views.home, name='register'),
    path('reg_form/', views.register, name='reg_form'),
    path('login/', views.user_login, name='login'),
    path('student_profile/', views.student_profile, name='student_profile'),
    path('warden_login/', views.warden_login, name='warden_login'),
    path('warden_login/leave', views.leave_admin, name='leave_admin'),
    path('warden_login/student_leaves/<int:std_id>/', views.student_leaves, name='student_leaves'),
    path('warden_login/leave_confirm/<int:lv_id>/', views.leave_confirm, name='leave_confirm'),
    path('warden_login/leave_reject/<int:lv_id>/', views.leave_reject, name='leave_reject'),
    path('warden_login/empty/', views.empty_rooms, name='empty_rooms'),
    path('warden_login/present_leaves/', views.present_leaves, name='present_leaves'),
    path('warden_login/mess_rebate/', views.mess_rebate, name='mess_rebate'),
    path('warden_login/guest_requests/', views.guest_requests, name='guest_requests'),
    path('warden_login/bookings/<int:b_id>/', views.bookings, name='bookings'),
    path('warden_login/confirm/<int:res_id>/', views.guest_accept, name='guest_accept'),
    path('warden_login/cancel/<int:res_id>/', views.guest_reject, name='guest_reject'),
    path('warden_profile/', views.warden_profile, name='warden_profile'),
    path('warden_dues/', views.warden_dues, name='warden_dues'),
    path('warden_add_due/', views.warden_add_due, name='warden_add_due'),
    path('warden_remove_due/', views.warden_remove_due, name='warden_remove_due'),
    path('hostels/', views.hostels, name='hostel_all'),
    path('hostels/<slug:hostel_name>/', views.hostel_detail_view, name='hostel'),
    path('login/edit/', views.edit, name='edit'),
    path('login/select/', views.select, name='select'),
    path('login/repair/', views.repair, name='repair'),
    path('logout/', views.logout_view, name='logout'),
    path('reg_form/login/edit/', views.edit, name='update'),
    path('BH5_GroundFloor/', views.BH5_GroundFloor, name='BH5_GroundFloor'),
    path('BH5_Floor1/', views.BH5_Floor1, name='BH5_Floor1'),
    path('BH5_Floor2/', views.BH5_Floor2, name='BH5_Floor2'),
    path('BH5_Floor3/', views.BH5_Floor3, name='BH5_Floor3'),
    path('BH5_Floor4/', views.BH5_Floor4, name='BH5_Floor4'),
    path('BH5_Floor5/', views.BH5_Floor5, name='BH5_Floor5'),
    path('BH5_Floor6/', views.BH5_Floor6, name='BH5_Floor6'),
    path('login/leave', views.user_leave, name='leave_status'),
]

guest/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.conf import settings
from selection.models import User


# Create your models here.

class Room(models.Model):
    # room_id = models.AutoField(primary_key=True)
    room_choice = [('S', 'Single Occupancy'), ('D', 'Double Occupancy')]
    no = models.CharField(validators=[MinLengthValidator(2)],max_length=5,unique=True)
    max_persons = models.IntegerField(default=2)
    room_type = models.CharField(choices=room_choice, max_length=1, default=None)
    price = models.IntegerField(default=500)

    def __str__(self):
        return 'Room no: %s price: %s' %(str(self.no), str(self.price))


class Reservation(models.Model):
    room = models.ForeignKey('Room', default=None,null=True, on_delete=models.CASCADE)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    checkIn = models.DateField()
    checkOut = models.DateField()
    booking_id = models.AutoField(primary_key=True)
    guest = models.ForeignKey('Guest', default=None, null=True, on_delete=models.CASCADE)
    room_alloted = models.BooleanField(default=False)
    accept = models.BooleanField(default=False)
    reject = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Reservation'

    def __str__(self):
        return str(self.booking_id)


class Guest(models.Model):
    user = models.OneToOneField(User,
                                default=None,
                                null=True,
                                on_delete=models.CASCADE)
    guest_id = models.AutoField(primary_key=True)
    first_name = models.CharField(validators=[MinLengthValidator(3)],max_length=255,null=True)
    last_name = models.CharField(validators=[MinLengthValidator(3)],max_length=255,null=True)
    phone = models.CharField(
        validators=[MinLengthValidator(5)],
        max_length=12,
        null=True,
    )
    email = models.EmailField(
        verbose_name='e-mail',
        null=True
    )
    city = models.CharField(
        max_length=20,null=True)
    # room = models.OneToOneField(
    #     'Room',
    #     blank=True,
    #     on_delete=models.CASCADE,
    #     null=True)
    # room_allotted = models.BooleanField(default=False)

    def __str__(self):
        return str(self.guest_id)

guest/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
import datetime
from .models import *

YEARS= [x for x in range(2018,2021)]


class UserForm(UserCreationForm):
    password1 = forms.CharField(min_length=8, max_length=30, widget=forms.PasswordInput(render_value=False))

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        help_texts = {
            'username': 'same as your roll no.',
        }

    # def clean_password(self):
    #     password = self.cleaned_data.get('password1')
    #     if len(password) < 8:
    #         raise ValidationError('Password too short')
    #     return super(UserCreationForm, self).clean_password1()


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class DateForm(forms.ModelForm):
    checkIn = forms.DateField(initial=datetime.date.today,widget=forms.SelectDateWidget(years=YEARS))
    checkOut = forms.DateField(initial=datetime.date.today,widget=forms.SelectDateWidget(years=YEARS))

    class Meta:
        model = Reservation
        fields = ['checkIn', 'checkOut', ]


class RegistrationForm(forms.ModelForm):
    class Meta:
        model = Guest
        fields = [
            'first_name',
            'last_name',
            'phone',
            'email',
            'city', ]


class SelectionForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['room', ]

guest/views.py
from django.db.transaction import commit
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import *
import datetime
from .models import Room,Reservation,Guest
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.template.loader import get_template
from .utils import render_to_pdf
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.


def start(request):
    return render(request, 'guest/start.html')


def register(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        # error1, error2 = False, False
        print(form.is_valid())
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.save()
            Guest.objects.create(user=new_user)
            cd = form.cleaned_data
            print(str(cd))
            user = authenticate(
                request,
                username=cd['username'],
                password=cd['password1'])

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('guest:home')
                else:

                    return HttpResponse('Disabled account')
            else:

                return HttpResponse('Invalid Login')
        else:
            form = UserForm()
            args = {'form': form}
            return render(request, 'reg_form.html', args)
        # elif len(form.data['password1']) <= 8 or len(form.data['password2']) <= 8:
        #     if len(form.data['password1']) <= 8:
        #         error1 = True
        #     if len(form.data['password2']) <= 8:
        #         error2 = True
        #     return render(request, 'reg_form.html', {'form': form, 'error1': error1, 'error2': error2})

    else:

        form = UserForm()
        args = {'form': form}
        return render(request, 'guest/reg_form.html', args)


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request,
                username=cd['username'],
                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('guest:home')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid Login')
    else:
        form = LoginForm()
        return render(request, 'guest/login.html', {'form': form})

@login_required
def home(request):
    print(request.method)
    if request.method == "POST":
        form = DateForm(request.POST)
        # response = HttpResponse()  # Created a HttpResponse
        # response['Cache-Control'] = 'no-cache'  # Set Cache-Control Header
        if form.is_valid():
            start_date = form.cleaned_data['checkIn']

            end_date = form.cleaned_data['checkOut']
            print(start_date, end_date)
            delta = end_date - start_date
            if delta.days > 0 and (start_date-datetime.date.today()).days >= 0:
                cnt = 0
                x = Room.objects.none()
                print(Room.objects.all())
                for room in Room.objects.all():
                    RoomsBooked = Reservation.objects.filter(room=room,room_alloted=True,accept=True).\
                        filter(checkIn__lte=end_date,checkOut__gte=start_date)
                    print(RoomsBooked)
                    count = RoomsBooked.count()
                    count = int(count)
                    if count == 0:
                        cnt += 1
                        x = x | Room.objects.filter(pk = room.pk)
                print(cnt)
                print(x)
                res = form.save(commit=False)
                if cnt > 0:

                    res.save()
                    request.session['booking_id'] = res.booking_id
                    # form.save(form.save(commit=False))
                    # form = SelectionForm(instance=request.reservation)
                    # form.fields["room"].queryset = x
                    args = {'rooms': x, 'count': cnt, 'res': res}
                    return render(request, 'guest/details.html', args)
                else:
                    return HttpResponse("<h1> No Rooms </h1> <br> <br> <a href =  '' >"
                                        " Book Again! </a> ")
            else:

                return HttpResponse("<h1> Invalid request </h1> <br> <br> <a href = '' >"
                                        " Book Again! </a> ")
        else:
            form = DateForm()
            print(request.method)
            return render(request, 'guest/home.html', {'form': form})

    else:
        form = DateForm()
        print(request.method)
        return render(request, 'guest/home.html', {'form': form})

@login_required
def edit(request, res_id):
    if request.method == 'POST':


        try:
            form = RegistrationForm(request.POST,instance=request.user.guest)
        except Guest.DoesNotExist:
            form = RegistrationForm(request.POST)

        # form = RegistrationForm(request.POST,instance=request.user.guest)
        res = Reservation.objects.get(pk=res_id)
        if form.is_valid():
            if (not res.room_alloted) and (request.session['room']):

                room = Room.objects.get(no=request.session['room'])
                res.room = room
                del request.session['room']


                try:
                    res.guest = request.user.guest
                    res.save()
                    form.save(commit=True)
                except Guest.DoesNotExist:
                    guest = form.save(commit=False)
                    guest.user = request.user
                    guest.save()
                    res.guest = guest

                    res.save()

                # res.guest = request.user.guest
                # res.save()

                return render(request, 'guest/profile.html', {'res': res})

            else:
                return HttpResponse("<h1> Invalid Request </h1>")
        else:
            res.delete()
            return HttpResponse("<h1> Wrong Credentials </h1> <br> <br> <a href = {% url '../../home' %} >"
                                " Book Again! </a> ")

    else:

        try:
            form = RegistrationForm(instance=request.user.guest)
        except Guest.DoesNotExist:
            form = RegistrationForm(request.POST)

        # form = RegistrationForm(instance=request.user.guest)
        return render(request, 'guest/edit.html', {'form': form,'res':res_id})


@login_required
def select(request, res_id):

    if request.method == 'POST':
        form = SelectionForm(request.POST, instance=Reservation.objects.get(pk=res_id))
        if form.is_valid():
            res_now = form.save(commit=False)
            # res_now.save()
            request.session['room'] = res_now.room.no
            # kwargs = {"room": res_now.room}
            return redirect('guest:edit', res_id =res_id)
    else:
        print('res_id',res_id)
        res = Reservation.objects.get(pk=res_id)
        form = SelectionForm(instance=res)
        start_date = res.checkIn
        end_date = res.checkOut
        x = Room.objects.none()
        print(Room.objects.all())
        cnt = 0
        for room in Room.objects.all():
            RoomsBooked = Reservation.objects.filter(room=room,room_alloted=True,accept=True).\
                filter(checkIn__lte=end_date, checkOut__gte=start_date)
            print(RoomsBooked.values())
            count = RoomsBooked.count()
            count = int(count)
            if count == 0:
                cnt += 1
                x = x | Room.objects.filter(pk=room.pk)
        if res.room:
            x = x | Room.objects.filter(pk=res.room.pk)
            cnt = cnt +1
        print(cnt)
        print(x)
        form.fields["room"].queryset = x
        return render(request, 'guest/select.html', {'form': form,'res':res})


@login_required
def bookings(request):
    try:
        guest = request.user.guest
        print(guest.first_name)
    except ObjectDoesNotExist:
        guest = Guest.objects.none()

    if guest:
        all_bookings = Reservation.objects.none()
        all_bookings = all_bookings | Reservation.objects.filter(guest=guest,room_alloted = True,accept=True)
        all_bookings = all_bookings | Reservation.objects.filter(guest=guest, room_alloted=True, reject=True)
        all_bookings = all_bookings | Reservation.objects.filter(guest=guest, room_alloted=True, accept=False,reject=False)
        print(all_bookings.count)
        return render(request,'guest/bookings.html',{"bookings":all_bookings,"guest":guest})
    elif request.user:

        return render(request, 'guest/bookings.html',{"bookings":Reservation.objects.none(),"guest":guest})


@login_required
def confirm(request,res_id):
    res = Reservation.objects.get(pk=res_id)

    res.room_alloted = True
    res.save()
    return render(request,'guest/confirm.html',{"res_id":res_id} )


@login_required
def generate_pdf(request,res_id):
    booking = Reservation.objects.get(pk = res_id)
    data = {
        'res': booking
    }
    pdf = render_to_pdf('guest/invoice.html', data)
    if pdf is None:
        booking.guest.delete()
        booking.delete()
        return HttpResponse("<h1>Error While Loading!! <br> Try Again</h1>")
    return HttpResponse(pdf, content_type='application/pdf')

@login_required
def cancel(request,res_id):
    booking = Reservation.objects.get(pk=res_id)
    booking.delete()

    return HttpResponse('<h1> Booking Cancelled </h1> <br> <a href=\"../../home\"> Book Again! </a>')


def logout_view(request):
    logout(request)
    return redirect('/guest')

guest/templates/guest/bookings.html
{% extends 'guest/base.html' %}

   {% block design %}

.s_book{

    padding: 30px;
    text-align: center; color: red ;


}

table.test td.test {
    background-color: lime;
    margin: 12px 12px 12px 12px;
    padding: 12px 12px 12px 12px;
}
table.test {
    border-collapse: separate;
    border-spacing: 10px;
    *border-collapse: expression('separate', cellSpacing = '10px');
}

    {% endblock design %}
{% block content %}



{% if bookings.count == 0 %}
<center><h4 class = 's_book'> No Bookings Done!!</h4></center>
{% else %}
<center> <h3 class = 's_book'> ALL Successful Bookings of {{guest.first_name}}  {{guest.last_name}} ({{guest.user.username}})</h3></center>
<!--<table class = 'test'>-->



            <!--<tr>-->
                <!--<th>-->
                   <!--ID-->
                <!--</th>-->
                <!--<th>-->
                    <!--Room No-->
                <!--</th>-->
                <!--<th>-->
                    <!--CheckIn-->
                <!--</th>-->
                <!--<th>-->
                    <!--CheckOut-->
                <!--</th>-->
            <!--</tr>-->
        <!--{% for booking in bookings %}-->
            <!--<tr>-->
                <!--<td class="test">-->
                   <!--{{booking.booking_id}}-->
                <!--</td>-->
                <!--<td class="test">-->
                    <!--{{booking.room.no}}-->
                <!--</td>-->
                <!--<td class="test">-->
                    <!--{{booking.checkIn}}-->
                <!--</td>-->
                <!--<td class="test">-->
                    <!--{{booking.checkOut}}-->
                <!--</td>-->



               <!--<td> <a class="btn btn-danger" href="{% url 'guest:cancel' booking.booking_id %}"> Cancel Booking </a>-->
               <!--</td>-->
            <!--</tr>-->
        <!--{% endfor %}-->


<!--</table>-->

<!--<br>-->


 <div class="wrapper" style="
    padding-top: 0px;">

        <div class="table">

            <div class="row header">
                <div class="cell">
                    ID
                </div>
                <div class="cell">
                    Room No
                </div>
                <div class="cell">
                    CheckIn
                </div>
                <div class="cell">
                    CheckOut
                </div>
                <div class="cell">
                    Status
                </div>
                <div class="cell">
                    Cancel
                </div>
            </div>
            {% for booking in bookings %}
                <div class="row">
                    <div class="cell" data-title="Number">
                        {{forloop.counter}}
                    </div>
                    <div class="cell" data-title="Number">
                        {{booking.room.no}}
                    </div>
                    <div class="cell" data-title="Date">
                         {{booking.checkIn}}
                    </div>
                    <div class="cell" data-title="Date">
                        {{booking.checkOut}}
                    </div>
                    <div class="cell" style="{% if booking.accept %} color: green {% elif booking.reject %} color:Red {% else %} color: blue {% endif %}"  data-title="status">

                        {% if booking.accept %}
                        Accepted
                        {% elif booking.reject %}
                        Rejected
                        {% else %}
                        Pending
                        {% endif %}

                    </div>

                    <div class="cell">
                        {% if booking.accept %}
                         <a class="btn btn-danger" href="{% url 'guest:cancel' booking.booking_id %}"> Cancel Booking </a>
                        {% elif booking.reject %}
                        Already Rejected
                        {% else %}
                         <a class="btn btn-danger" href="{% url 'guest:cancel' booking.booking_id %}"> Cancel Booking </a>
                        {% endif %}
                    </div>

                </div>
            {% endfor %}
        </div>

    </div>
 <br>
{% endif %}

{% endblock content %}




{% block more_links %}
    <a href="{% url 'guest:home' %}"> Book A Room! </a>
    <a href="{% url 'guest:logout' %}">Logout</a>
{% endblock more_links %}

guest/templates/guest/details.html
{% extends 'guest/base.html' %}
{% block design %}
<!--table {-->
    <!--font-family: arial, sans-serif;-->
    <!--border-collapse: collapse;-->
    <!--width: 100%;-->
<!--}-->

<!--td, th {-->
    <!--border: 1px solid #dddddd;-->
    <!--text-align: left;-->
    <!--padding: 8px;-->
<!--}-->

<!--tr:nth-child(even) {-->
    <!--background-color: #dddddd;-->
<!--}-->

{% endblock design %}

{% block content %}


{% if count %}

<h1 style="color:Tomato;text-align: center;" > Available No of rooms ..  {{ count }} </h1>
<!--<table>-->


     <!--<tr>-->
        <!--<th> Room No.. </th>-->
        <!--<th> Price</th>-->
     <!--</tr>-->


    <!--{% for room in rooms %}-->

     <!--<tr>-->
        <!--<td> {{room.no}} </td>-->
        <!--<td> {{room.price}} </td>-->
    <!--</tr>-->

    <!--{% endfor %}-->


<!--</table>-->

<div class="wrapper" style="
    padding-top: 40px;
    padding-bottom: 0px;
    padding-left: 0px;
    padding-right: 0px;
">

        <div class="table">

            <div class="row header">
                <div class="cell">
                    Room No
                </div>
                <div class="cell">
                    Price
                </div>
                <div class="cell">
                    Max Persons
                </div>

            </div>
            {% for room in rooms %}
                <div class="row">
                    <div class="cell" data-title="Number">
                        {{room.no}}
                    </div>
                    <div class="cell" data-title="Name">
                        {{room.price}}
                    </div>
                    <div class="cell" data-title="Name">
                        {{room.max_persons}}
                    </div>

                </div>
            {% endfor %}
        </div>
    </div>



<div class="center" style = "text-align: center;" >
<a class="btn btn-primary" href="{% url 'guest:select' res.booking_id %}"> Select a Room </a>
</div>

{% else %}
<h1>No Rooms Available</h1>
{% endif %}

<!--<div class="wrap">-->
    <!--<form action="" method="post">-->
        <!--{% csrf_token %}-->
      <!--<div class="fields">{{ form.as_p }}</div>-->
      <!--<input class="button-custom" type="submit" value="SELECT">-->
    <!--</form>-->
  <!--</div>-->


{% endblock content %}




{% block more_links %}
    <!--<a href="{% url 'login' %}">Login</a>-->
    <!--<a href="{% url 'reg_form' %}">Register</a>-->
    <a href="{% url 'guest:cancel' res.booking_id %}">Cancel Booking</a>
   <a href="{% url 'guest:logout' %}">Logout</a>

{% endblock more_links %}

guest/templates/guest/edit.html
{% extends 'guest/base.html' %}

{% block content %}


<!--<div class = "guest">-->
<!--<form action="" method="post">-->
    <!--{% csrf_token %}-->
    <!--{{ form.as_p }}-->
    <!--<input type="submit" class = "btn btn-primary" value="Submit">-->
<!--</form>-->

<!--</div>-->

<div class="wrap">
    <form action="" method="post">
        {% csrf_token %}
      <div class="fields"> First Name <br><br> {{ form.first_name }}</div>
      <div class="fields"> Last Name <br><br> {{ form.last_name }}</div>
      <div class="fields"> Phone Number <br><br> {{ form.phone }}</div>
      <div class="fields"> E-mail <br><br> {{ form.email }}</div>
      <div class="fields"> City  <br><br> {{ form.city }}</div>
      <input type="submit" class = "btn btn-primary" value="Submit">
    </form>
  </div>

{% endblock content %}




{% block more_links %}
    <!--<a href="{% url 'login' %}">Login</a>-->
    <!--<a href="{% url 'reg_form' %}">Register</a>-->
        <a href="{% url 'guest:cancel' res %}">Cancel Booking</a>
       <a href="{% url 'guest:logout' %}">Logout</a>
{% endblock more_links %}

guest/templates/guest/home.html
{% extends 'guest/base.html' %}

{% block content %}


<div class="wrap">
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class = "btn btn-primary" value="CHECK AVAILABILITY">
</form>

</div>

{% endblock content %}




{% block more_links %}
    <a href="{% url 'guest:bookings' %}">My Bookings</a>
    <a href="{% url 'guest:logout' %}">Logout</a>

{% endblock more_links %}

guest/templates/guest/login.html
{% extends 'guest/base.html' %}

{% block content %}
<div class="wrap">
    <form action="" method="post">
        {% csrf_token %}
      <div class="fields"> Username <br><br> {{ form.username }}</div>
      <div class="fields"> Password <br><br> {{ form.password }}</div>
      <input class="button-custom" type="submit" value="LOGIN">
    </form>
  </div>
{% endblock content %}


{% block more_links %}
    <a href="{% url 'guest:login' %}">Login</a>
    <a href="{% url 'guest:register' %}">Register</a>
{% endblock more_links %}

guest/templates/guest/profile.html
{% extends 'guest/base.html' %}

{% block content %}

    <div class="wrapper">
        <div class="table">

            <div class="row">
                <div class="cell">
                    First Name
                </div>
                <div class="cell">
                    {{ res.guest.first_name }}
                </div>
            </div>
            <div class="row">
                <div class="cell">
                    Last Name
                </div>
                <div class="cell">
                    {{ res.guest.last_name}}
                </div>
            </div>
            <div class="row">
                <div class="cell">
                    Phone no
                </div>
                <div class="cell">
                    {{ res.guest.phone }}
                </div>
            </div>
            <div class="row">
                <div class="cell">
                    E-Mail
                </div>
                <div class="cell">
                    {{ res.guest.email }}
                </div>
            </div>
            <div class="row">
                <div class="cell">
                    city
                </div>
                <div class="cell">
                    {{ res.guest.city }}
                </div>
            </div>
            <div class="row">
                <div class="cell">
                    Room
                </div>
                <div class="cell">
                     {{ res.room.no }} in Guest House

                </div>
            </div>
            <div class="row">
                <div class="cell">
                    Price (&#x20b9;)
                </div>
                <div class="cell">
                     {{res.room.price}}
                </div>
            </div>
            <div class="row">
                <div class="cell">
                    CheckIn
                </div>
                <div class="cell">
                     {{ res.checkIn }}

                </div>
            </div>

            <div class="row">
                <div class="cell">
                    CheckOut
                </div>
                <div class="cell">
                     {{ res.checkOut }}

                </div>
            </div>
        </div>
    </div>


    <div style=" margin: 0 auto;
            padding: 40px;
            max-width: 800px;text-align:center;">
            <a class="btn btn-success" href="{% url 'guest:confirm' res.booking_id %}"> Confirm Booking </a>

            <a class="btn btn-danger" href="{% url 'guest:cancel' res.booking_id %}"> Cancel Booking </a>

            <!--<a class="btn btn-success" href="{% url 'guest:pdf' res.booking_id %}"> Generate PDF </a>-->
    </div>


{% endblock content %}


{% block more_links %}
   <a href="{% url 'guest:logout' %}">Logout</a>
{% endblock more_links %}

guest/templates/guest/reg_form.html
{% extends 'guest/base.html' %}

{% block content %}
<div class="wrap">
    <form  method="post" action = "">
        {% csrf_token %}
      <div class="fields"> Username <br><br> {{ form.username }}</div>


      <div class="fields"> Password <br><br>
           <div class = 'error1' >
             {% if error1 %}
        <p style="color: red;">
            Please enter password of atleast 8 characters or more.
        </p>
        {% endif %}
        </div>
          {{ form.password1 }}
      </div>



      <div class="fields"> Repeat Password <br><br>
          <div class="error2">
            {% if error2 %}
        <p style="color: red;">
            Please enter confirm password (same as password)
        </p>
        {% endif %}
              </div>
          {{ form.password2 }} </div>

      <input class="button-custom" type="submit" value="REGISTER">
    </form>
  </div>
{% endblock content %}

{% block more_links %}
    <a href="{% url 'guest:login' %}">Login</a>
    <a href="{% url 'guest:register' %}">Register</a>
{% endblock more_links %}

guest/templates/guest/select.html
{% extends 'guest/base.html' %}

{% block content %}
<div class="wrap">
    <form action="" method="post">
        {% csrf_token %}
      <div class="fields">{{ form.as_p }}</div>
      <input class="button-custom" type="submit" value="SELECT">
    </form>
  </div>

{% endblock content %}


{% block more_links %}
    <a href="{% url 'guest:cancel' res.booking_id %}">Cancel Booking</a>
       <a href="{% url 'guest:logout' %}">Logout</a>
        <!--<a href="{% url 'select' %}">-->
            <!--Select a Room-->
        <!--</a>-->
        <!--<a href="{% url 'logout' %}">-->
            <!--Logout-->
        <!--</a>-->
{% endblock more_links %}